apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: eks-dev-argo-frontend
  newName: 361555779387.dkr.ecr.ap-southeast-1.amazonaws.com/ecr-nashtech-devops-frontend
  newTag: "52"
resources:
- _deployment.yaml
- _service.yaml
